- name: Preflight
  tags: always
  include_tasks: "{{ _os }}/00-preflight.yml"

- name: Install and configure Vault
  tags: config
  include_tasks: "{{ _os }}/01-install.yml"

- name: Manage configs
  tags: config
  include_tasks: "{{ _os }}/02-configs.yml"
