driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - &node
    name: windows
    box: gusztavvargadr/windows-server-2019-standard-core
    memory: 512
    cpu: 1
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"

provisioner:
  name: ansible
  connection_options:
    ansible_port: 5985
    ansible_connection: winrm
    ansible_winrm_scheme: http

verifier:
  name: testinfra
  directory: ../tests
  env:
    # get rid of the DeprecationWarning messages of third-party libs,
    # see https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    # show which tests where executed in test output
    v: 1
